### ISSUE TITLE
Requisition for Glove Training Code

### ISSUE THREAD

**Issue by JBYan** [enry12/adversarial_training_methods#5]
Hello Enrico,
Thank you for your code. I'm facing a multi-classification problem of text. Luckly, I find your code can help me, And I want to learn more about your code. However,  the script for GloVe training is missing here. So, could you please send me the script or update it?
Thanks a lot for your help!
yan
Email: jianbo_y@126.com

**Comment by enricivi** [comment]
Hello Yan,

We are really happy that our code helps you in your project.

The script to train GloVe is missing because you can find it on https://nlp.stanford.edu/projects/glove/.
You have to slightly modify the configuration file (according to our README) in order to set the correct embedding vectors proprierties.

Here a snapshot of the site:
Getting started (Code download)
 - Download the code (licensed under the Apache 
   License, Version 2.0)
 - Unpack the files:  unzip GloVe-1.2.zip
 - Compile the source:  cd GloVe-1.2 && make
 - Run the demo script: ./demo.sh
 - Consult the included README for further usage 
   details

Enrico
